### ISSUE TITLE
Skyblock Arena

### ISSUE THREAD

**Issue by PrOsKiTtLeSs** [x0Z3ro0x/DKG-MC-Server#10]
I got to round 6, when there was a swarm attack of killer bunnys, when i tried to kill them, i didn't have permission to kill them, so i had no way of killing the rabbits and consequently died

**Comment by x0Z3ro0x** [comment]
Which arena is this please :)

**Comment by PrOsKiTtLeSs** [comment]
This was in arena 2

**Comment by x0Z3ro0x** [comment]
Awesome thanks, I will start looking into this immediately. Break more stuff!

**Comment by x0Z3ro0x** [comment]
This is now solved. Thanks for the bug report!
