### ISSUE TITLE
Arena 4 skyblock

### ISSUE THREAD

**Issue by PrOsKiTtLeSs** [x0Z3ro0x/DKG-MC-Server#11]
When spawning into Arena 4, you spawn in the floor in front of the class selection, but since you spawn in the floor, causing you to fall into the arena as soon as you spawn, so you can't select the class or ready up. Meaning you're stuck in the arena without any enemies or weapons

**Comment by x0Z3ro0x** [comment]
I will need further testing on this. We were playing 4 last night and never had that happen. Thank you for the report, I will investigate this after I solve arena 2.

**Comment by x0Z3ro0x** [comment]
This issue was called by not having the lobby defined. Thank you for pointing it out. This issue is now solved.
