### ISSUE TITLE
SkyBlock /mvspanwn issue

### ISSUE THREAD

**Issue by PrOsKiTtLeSs** [x0Z3ro0x/DKG-MC-Server#2]
When i tried /mvspawn to get back to spawn it tp'd me into the void. so i ended up dying. may need fixing XD good job on it all as a whole though, server is great

**Comment by x0Z3ro0x** [comment]
This should be solved now. Will need further testing to confirm it.

**Comment by x0Z3ro0x** [comment]
This should be solved now. Will need further testing to confirm it.

**Comment by x0Z3ro0x** [comment]
I'm gonna mark this solved and close it, if it's not solved please open another ticket.
