### ISSUE TITLE
mcMMO Rates

### ISSUE THREAD

**Issue by x0Z3ro0x** [x0Z3ro0x/DKG-MC-Server#3]
Job ID: 

- 001

Details: 

- mcMMO has been added to the users, details can be found in the Projects section. What we need most is to begin testing the rates and features to find out what can be abused, what needs adjusted, and what should be added that isn't currently. This will take a rather long time. Testing won't be short as there are several abilities, skills, perks, and in general, features to test. We can get into further details if you should accept the job.

- This is also something that will sort its self out over time as users play and we notice what they have earned and haven't earned as well as feedback from them. Users aren't shy to tell us what is missing or what they can't do that they feel they should be able to. These facts allow for this kind of testing to sort its self out with nothing more than time. For this reason this testing is Medium Priority as we would like to get it done, but in all honesty, testers are not needed.

Estimated Testing Time:

- 1 - 3 Months

Current Testers:

- Proskittless

**Comment by PrOsKiTtLeSs** [comment]
I’ll test it bud

**Comment by x0Z3ro0x** [comment]
How is the testing on this coming?

**Comment by PrOsKiTtLeSs** [comment]
Good, I’m going through the ranks and making note of any that don’t work
(none so far)
