### ISSUE TITLE
Shop suggestion

### ISSUE THREAD

**Issue by PrOsKiTtLeSs** [x0Z3ro0x/DKG-MC-Server#8]
I'm not sure if this already in the making, but a server sellshop in survival spawn. similar to the one at skyblock but items that would benefit survival players more, like  ingots, gems, even players selling stuff to the server.

**Comment by x0Z3ro0x** [comment]
We did have a card for this. But we removed it figuring players would just rent shops of their own, or use the jobs board to buy and sell. If you think players would find enough use out of it, I would be willing to add one.

**Comment by PrOsKiTtLeSs** [comment]
i think it'd be more useful than the player shops, it could give players another way to earn money to help start up and progress towards a rent shop. but it'll still be useful later on in the game with people wanting to fight bosses, needing some items like bottle o' enchanting for example, players cant normally get them so it could be a possibility to add those or diamonds, spawn eggs for farms etc

**Comment by x0Z3ro0x** [comment]
Ok I think we can make something. I will rent out one of the player shops until we can get more players. I would like some form of event or quest to be completed that gives those things out. Rather than just buying them. What do you think?

**Comment by PrOsKiTtLeSs** [comment]
Sounds great

**Comment by x0Z3ro0x** [comment]
Added a buy shop rather than a sell shop, so that players have a way to earn money, but can't use a server shop to fast track progress. Instead they will either need to earn, or buy it from other players. Add this to the completed list :)
